### ISSUE TITLE
Add music when not inside a game

### ISSUE THREAD

**Issue by Jasperav** [RensArts/chad-bird-game#8]
Would be nice to hear some music playing when i am buying skins and just on the main screen

**Comment by RensArts** [comment]
I haven't figured out a way to implement music which autoplays on opening of the browser, it does not seem to be possible without the user having to click something first. This will be very annoying if you switch stores or go to the settings menu as the music will stop and restart constantly. 

Uncaught DOMException DOMException: play() failed because the user didn't interact with the document first.
